name: ItemLimister
version: '1.1'
main: me.renssus.itemLimister.ItemLimister
api-version: '1.21'

commands:
  itemlimiter:
    description: Reload the item limiter config
    usage: /itemlimiter reload
    aliases: [il]